### Status
GET {{baseUrl}}/status

### Login
POST {{baseUrl}}/login
Content-Type: application/x-www-form-urlencoded

username=nainfauxeninfo&password={{password}}

### Get hashtag
GET {{baseUrl}}/hashtags/naturopathie?refresh=false

### Get specific hashtag to check
GET {{baseUrl}}/checks/sport

### Get all hashtags to check
GET {{baseUrl}}/checks

### Save hashtag to list
POST {{baseUrl}}/checks/sport

### Get related hashtags
GET {{baseUrl}}/hashtags/sport/related