### Status
GET {{baseUrl}}/status

### Login
POST {{baseUrl}}/login
Content-Type: application/x-www-form-urlencoded

username=nainfauxeninfo&password={{password}}

### Get hashtag
GET {{baseUrl}}/hashtags/naturopathie?refresh=false

### Save hashtag to list
POST {{baseUrl}}/hashtags/naturopathie

### Get hashtag from list of to check
GET {{}}