"""Initial tables

Revision ID: ec731c828612
Revises: 
Create Date: 2023-01-02 14:40:25.214246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec731c828612'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hashtag_check',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('media_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('time')
    )
    op.create_table('hashtag_to_check',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('hashtag_id', sa.String(length=128), nullable=True),
    sa.Column('last_check', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    op.execute("SELECT create_hypertable('hashtag_check', 'time');")
    op.execute("CREATE INDEX ix_name_time ON hashtag_check(name, time DESC);")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hashtag_to_check')
    op.drop_table('hashtag_check')
    # ### end Alembic commands ###
